#ifndef _SSH_TYPEDEF_H
#define _SSH_TYPEDEF_H

#ifndef Boolean
#define Boolean int
#endif

#ifndef TRUE
#define TRUE 1
#endif

#ifndef FALSE
#define FALSE 0
#endif

//error code
#define SSH_TERMINAL_GETADDRINFO_ERROR -1
#define SSH_TERMINAL_SOCKET_ERROR -2
#define SSH_TERMINAL_SESSION_INIT_ERROR -3
#define SSH_TERMINAL_SESSION_STARTUP_ERROR -4
#define SSH_TERMINAL_USERAUTH_ERROR -5
#define SSH_TERMINAL_NO_SESSION_ERROR -6
#define SSH_TERMINAL_SESSION_DISCONNECT_ERROR -7
#define SSH_TERMINAL_COMMAND_TIMEOUT -8
#define SSH_TERMINAL_CHANNEL_OPEN_ERROR -9
#define SSH_TERMINAL_COMMAND_EXEC_ERROR -10
#define SSH_TERMINAL_NOT_RUN_THREAD_ERROR -11
#define SSH_TERMINAL_ASYNC_MODE_ERROR -12
#define SSH_TERMINAL_COMMAND_INIT_ERROR -13
#define SSH_TERMINAL_ALREADY_RUN_THREAD -14
#define SSH_TERMINAL_NOT_INIT_THREAD -15
#define SSH_TERMINAL_REQUEST_PTY_ERROR -16
#define SSH_TERMINAL_SHELL_ERROR -17
#define SSH_TERMINAL_ALREADY_CHANNEL_OPEN -18
#define SSH_TERMINAL_INVALID_CHANNEL_TYPE -19
#define SSH_TERMINAL_CHANGE_PTY_SIZE_ERROR -20
#define SSH_TERMINAL_NOT_OPEN_CHANNEL -21
#define SSH_TERMINAL_CHANNEL_READ_ERROR -22

//ssh_channel_type
#define CHANNEL_TYPE_EXEC 0
#define CHANNEL_TYPE_SHELL 1

//default pty size
#define DEFAULT_PTY_SIZE_WIDTH 85
#define DEFAULT_PTY_SIZE_HEIGHT 40

#define COMMAND_RESULT_BUFFER_LENGTH 0x8000
#define COMMAND_QUEUE_MAX_SIZE 500
#define TIMEOUT_SEC 30

#endif